# Generated by Django 3.0.7 on 2020-06-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaignpage_donateindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignpage',
            name='donor',
        ),
    ]
