# Generated by Django 3.0.7 on 2020-06-13 23:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('campaign', '0004_remove_campaignpage_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_donated', models.DateField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='campaign.CampaignPage')),
                ('person_page', models.ForeignKey(blank=True, help_text='You can only search for a Published person page. "Create New" only works if you have Publish permissions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Page')),
            ],
        ),
    ]
