# Generated by Django 3.0.7 on 2020-06-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
