# Generated by Django 3.0.7 on 2020-07-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtcrew', '0009_auto_20200613_1641'),
        ('campaign', '0006_donor_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignpage',
            name='interest_form',
            field=models.ForeignKey(blank=True, help_text='Provide a FormPage for users to submit interest in donating.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gtcrew.FormPage'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Internal use only. Amount remains hidden from the public.', max_digits=9),
        ),
        migrations.AlterField(
            model_name='donor',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='"Anonymous" will replace name of donor on campaign page.'),
        ),
    ]
