# Generated by Django 3.0.8 on 2020-08-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20200728_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='"George P. Burdell" will replace name of donor on campaign page.'),
        ),
    ]
