# Generated by Django 3.0.8 on 2020-08-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20200813_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='last_modified_by',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
