# Generated by Django 3.1.6 on 2021-03-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20200815_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Optional if Person Page is linked.', max_length=255),
        ),
    ]
