# Generated by Django 3.2.5 on 2021-07-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_alter_donor_id'),
        ('campaign', '0010_donor_display_name'),
    ]

    operations = [
    ]
