# Generated by Django 4.1.10 on 2023-12-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_alter_donateindexpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignpage',
            name='donor_goal',
            field=models.PositiveIntegerField(default=0, help_text='Leave as zero if you do not want a goal regarding the number of donors.'),
        ),
    ]
