# Generated by Django 2.0.7 on 2019-02-14 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gtid',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\d){9}$')], verbose_name='GT ID'),
        ),
    ]
