# Generated by Django 2.0.7 on 2019-02-23 20:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20190213_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Profile')),
            ],
        ),
        migrations.AlterModelManagers(
            name='membership',
            managers=[
                ('students', django.db.models.manager.Manager()),
            ],
        ),
    ]
