# Generated by Django 3.0.4 on 2020-03-29 19:34

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20200328_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='header1',
        ),
        migrations.RemoveField(
            model_name='page',
            name='header2',
        ),
        migrations.RemoveField(
            model_name='page',
            name='text',
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[700, 700], upload_to=''),
        ),
    ]
