# Generated by Django 2.0.7 on 2019-02-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20190223_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'email addresses'},
        ),
    ]
