# Generated by Django 3.0.4 on 2020-04-08 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_profile_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['year', '-semester']},
        ),
    ]
