# Generated by Django 3.0.4 on 2020-04-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20200411_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['last_name']},
        ),
    ]
