# Generated by Django 3.0.4 on 2020-04-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20200415_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
