# Generated by Django 3.0.4 on 2020-06-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20200415_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=64, null=True, unique=True),
        ),
    ]
