# Generated by Django 3.0.4 on 2020-06-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
