# Generated by Django 3.0.4 on 2020-06-08 22:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_auto_20200606_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='description',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
