# Generated by Django 3.0.4 on 2020-06-08 22:55

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_auto_20200608_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=1500),
        ),
    ]
