# Generated by Django 3.0.4 on 2020-06-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20200608_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='profiles',
            field=models.ManyToManyField(blank=True, through='team.AwardGiven', to='team.Profile'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='profiles',
            field=models.ManyToManyField(blank=True, through='team.Membership', to='team.Profile'),
        ),
        migrations.AlterField(
            model_name='title',
            name='profiles',
            field=models.ManyToManyField(blank=True, through='team.Membership', to='team.Profile'),
        ),
    ]
