# Generated by Django 3.0.8 on 2020-08-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_auto_20200713_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='page',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
