# Generated by Django 3.0.8 on 2020-08-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_auto_20200815_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardgiven',
            name='award',
        ),
        migrations.RemoveField(
            model_name='awardgiven',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='AwardGiven',
        ),
    ]
