# Generated by Django 3.0.4 on 2020-04-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0010_auto_20200415_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('shell', 'Racing Shell'), ('motor', 'Motor'), ('erg', 'Erg'), ('other', 'Other')], default='shell', max_length=6)),
                ('acquisition_date', models.DateField(blank=True, help_text='Date of purchase.')),
                ('acquisition_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('retirement_date', models.DateField(blank=True, help_text='Date removed from service.')),
                ('retirement_reason', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_created', to='team.Profile')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_last_modified', to='team.Profile')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
