# Generated by Django 3.0.4 on 2020-04-19 03:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20200415_2332'),
        ('asset', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_created',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to='team.Profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_last_modified', to='team.Profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='coxswain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results_coxed', to='team.Profile'),
        ),
        migrations.AddField(
            model_name='result',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_created', to='team.Profile'),
        ),
        migrations.AddField(
            model_name='result',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_last_modified', to='team.Profile'),
        ),
        migrations.AddField(
            model_name='result',
            name='minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='rowers',
            field=models.ManyToManyField(related_name='results_rowed', to='team.Profile'),
        ),
        migrations.AddField(
            model_name='result',
            name='seconds',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59.999)]),
        ),
        migrations.AddField(
            model_name='result',
            name='shell',
            field=models.ForeignKey(blank=True, limit_choices_to='shell', null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.Asset'),
        ),
        migrations.AlterField(
            model_name='result',
            name='distance',
            field=models.PositiveIntegerField(help_text='meters'),
        ),
        migrations.AlterField(
            model_name='result',
            name='event',
            field=models.ForeignKey(blank=True, limit_choices_to={'event_type': 'Race'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.CharField(help_text='Name of Result', max_length=64),
        ),
        migrations.AlterField(
            model_name='result',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.Squad'),
        ),
    ]
