# Generated by Django 2.0.7 on 2019-02-14 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='distance',
            field=models.IntegerField(blank=True, help_text='meters', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='result',
            name='time',
            field=models.CharField(blank=True, help_text='MM:SS.mmm', max_length=9, null=True, validators=[django.core.validators.RegexValidator('^(\\d){2}:(\\d){2}.(\\d){3}$')], verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
