# Generated by Django 3.0.4 on 2020-04-19 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20200419_0013'),
        ('event', '0002_auto_20200418_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='shell',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'shell'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.Asset'),
        ),
    ]
