# Generated by Django 2.0.7 on 2019-02-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190213_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='event',
        ),
        migrations.RemoveField(
            model_name='result',
            name='squad',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
