# Generated by Django 3.0.4 on 2020-04-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20200415_2332'),
        ('event', '0003_auto_20200419_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='rowers',
            field=models.ManyToManyField(blank=True, related_name='results_rowed', to='team.Profile'),
        ),
    ]
