# Generated by Django 3.0.4 on 2020-05-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20200415_2332'),
        ('event', '0005_result_personal_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='lightweight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='squads',
            field=models.ManyToManyField(blank=True, null=True, to='team.Squad'),
        ),
    ]
