# Generated by Django 3.0.4 on 2020-05-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20200415_2332'),
        ('event', '0008_result_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='time',
        ),
        migrations.AlterField(
            model_name='event',
            name='squads',
            field=models.ManyToManyField(blank=True, to='team.Squad'),
        ),
    ]
