# Generated by Django 3.0.7 on 2020-06-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_eventindexpage_eventpage_regatta_resultpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regatta',
            old_name='name',
            new_name='title',
        ),
    ]
