# Generated by Django 3.0.8 on 2020-08-13 19:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_auto_20200713_2157'),
        ('event', '0012_racers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('distance', models.PositiveIntegerField(help_text='meters')),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('seconds', models.DecimalField(decimal_places=3, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59.999)])),
                ('lightweight', models.BooleanField(default=False)),
                ('pace', models.FloatField(default=0, editable=False)),
                ('entry', models.CharField(help_text='E.g. "Lightweight Varsity 8+"', max_length=64)),
                ('rank', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='event.EventPage')),
                ('squad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='team.Squad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
