# Generated by Django 3.0.8 on 2020-08-13 19:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_auto_20200713_2157'),
        ('wagtailcore', '0052_pagelogentry'),
        ('event', '0013_resultinline'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacerInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='racers', to='event.ResultInline')),
                ('person_page', models.ForeignKey(blank=True, help_text='You can only search for a Published person page. "Create New" only works if you have Publish permissions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Page')),
                ('position', models.ForeignKey(blank=True, limit_choices_to={'held_by': 'racer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='team.Title')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
