# Generated by Django 3.0.8 on 2020-08-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('event', '0014_racerinline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='resultpage',
            name='squad',
        ),
        migrations.DeleteModel(
            name='Racers',
        ),
        migrations.DeleteModel(
            name='ResultPage',
        ),
    ]
