# Generated by Django 3.0.8 on 2020-08-15 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20200813_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='coxswain',
        ),
        migrations.RemoveField(
            model_name='result',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='result',
            name='event',
        ),
        migrations.RemoveField(
            model_name='result',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='result',
            name='rowers',
        ),
        migrations.RemoveField(
            model_name='result',
            name='shell',
        ),
        migrations.RemoveField(
            model_name='result',
            name='squad',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
