# Generated by Django 3.0.8 on 2020-08-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('event', '0017_auto_20200814_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='person_page',
            field=models.ForeignKey(blank=True, help_text='You can only search for a Published person page. "Create New" only works if you have Publish permissions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results_raced', to='wagtailcore.Page'),
        ),
    ]
