# Generated by Django 3.2.11 on 2022-03-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20210724_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='event_type',
            field=models.CharField(choices=[('Race', 'Race'), ('Training', 'Training'), ('Administrative', 'Administrative'), ('Social', 'Social')], default='Race', max_length=64, verbose_name='Type'),
        ),
    ]
