# Generated by Django 3.0.4 on 2020-04-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
