# Generated by Django 3.0.4 on 2020-04-19 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20200415_2332'),
        ('story', '0004_story_page_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stories_last_modified', to='team.Profile'),
        ),
        migrations.AlterField(
            model_name='story',
            name='profiles_mentioned',
            field=models.ManyToManyField(related_name='stories_mentioned', to='team.Profile'),
        ),
    ]
