# Generated by Django 3.0.4 on 2020-04-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20200415_2332'),
        ('story', '0005_auto_20200419_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='profiles_mentioned',
            field=models.ManyToManyField(blank=True, related_name='stories_mentioned', to='team.Profile'),
        ),
    ]
