# Generated by Django 3.0.8 on 2020-08-20 01:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_auto_20200815_0122'),
        ('person', '0004_personalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnedAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=team.models.get_default_year)),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='team.Award')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_awards', to='person.PersonPage')),
            ],
        ),
    ]
