# Generated by Django 3.0.8 on 2020-08-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_earnedaward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EarnedAward',
        ),
    ]
