# Generated by Django 4.1.13 on 2024-04-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_personalrecord_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalrecord',
            options={'ordering': ['-date', 'pace']},
        ),
    ]
