# Generated by Django 3.2.12 on 2022-03-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0002_remove_shellpage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shellpage',
            name='date_decommissioned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
