# Generated by Django 3.0.4 on 2020-06-08 00:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('gtcrew', '0002_auto_20200607_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.core.fields.StreamField([('post', wagtail.core.blocks.StructBlock([('heading_small', wagtail.core.blocks.CharBlock()), ('heading_large', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False))])), ('html', wagtail.core.blocks.RawHTMLBlock())]),
        ),
    ]
