# Generated by Django 3.0.7 on 2020-06-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_auto_20200611_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'Coaches'},
        ),
    ]
