# Generated by Django 3.2.8 on 2021-10-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_auto_20210724_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Coaches'},
        ),
    ]
